language: java
before_deploy: gradle jar addon
deploy:
  provider: releases
  api_key:
    secure: j/MKb1fY56mEqZy/K/dR+BY4zZaxY/hlPoDHoIFFs3mJtQcB7KAPOkBoWzwfuj5FALde4W84aWssckkPKX65ZS/cSt4iZ+ZVnkwYatNTl4TXEd60eoZuogPNPliXUc7rvgflqgokq4SD9RErCxc0/cI25uwafupJbTL+V4kKlwOYvq5d72maLn/D5XDDhQ6e2KsilsK3JXmwVXEs7UkSQibxQQOQ8stjL2SaUdAxAwHInUp6TmdhSvK57uaqdEj9VPnsw0dqXSgSp8MopyfmMMGGHgY5xm3ZT9iU163o4qVYdyeLuSc/jnqmb0oe3/GpgGszv+FI/0pBsgjbsYZoNwT2ovjoTdRDFBmQswXWUtr5cb1JPDkBZbKVvgm/Ml3UkaXLYDX0Uel8tW9bPhaM92L2OpQAKiF7ApJ0iQGAlO7rJxMwCZ4KgFkFkkjHnWfvD0MHxTI+EpG2vcoIm4YhenzXINKYFm5CvbZhHRG2nJQEb44Oy5Ot/Ipri2Y084YSbsulRbucIm3lAlYduXqLKTucJxtcp7HjkQZhraCDWDCAFA5v1WPTLnOdxGpmFyTNFMPjRFdevfWoXcfZzlEtaAnYB0pQOVPKW6aWs1/LD2OZ9a3sLIY6FaP93cQEJvuGtbMJ62Bh9TeEsUNv5GUkBCe4hBfM861UV007M1J03PA=
  file:
  - build/libs/hm2mqtt.jar
  - build/distributions/hm2mqtt-addon.tar.gz
  skip_cleanup: true
  on:
    repo: hangy/hm2mqtt
    tags: true
    all_branches: true
