language: java
before_deploy: "gradle jar addon"
deploy:
  provider: releases
  api_key:
    secure: Pqw0pxtdJ4tT4WiugX9vazfCgRaJn/PQqxJ6BnLcr3S2MoELNWqvFn3LOAj/X9dU9yUFvCD7zRZaVkRpgLNbBCZDjRvuLNE1wt6VucT/9bJSHgEEix6HarKprsO8dV7t838PxlyQGPcNmRCk/aDXGeutH2owDbFQcsp8jVtaPSofyEl6f482qDb0++KBT7rn+CPZL9H7+No76WtMmpy0L3NAPDjRKStZN7v4uNAycU2n398dMwHUP6o6P88VGsTq9628o/6HpkjWtTWTKDXMSG3LIQJtEA2eOuVLdZEZfDTqMMEb/QkjQvA469/JyqcHvnRIAjBrLDJozGBZoRfAa8NeuoVQZkUvLNKKYyRqeAylciGK9lc9tivIjVirSmi9jKzdKmtCiUUibZ7WujAmXg6eMa1wxCobYQXwiWX/Y6D1iHKolBKXBEPcYIlllo0yvCpBOaXKjD5W+k7cI/sFkdXkOKh0f5VamtWwcZ1hUrovnQpnBqtv6UDNiL1leY80SUdjaM7h4JDZ9e5ft89/pUDCo8nEgZJb7xJP327mxA+atha4/OoztVnoVXk7wi+Q+GAxfCEH3mU5Z+lZS7jvbqX4vpLKm+cBjRbx8ktpEyOJzi9Nn5/vNs0gBRS39JUm1f01lnmahsJSfblhm0BB7b5dtc1YOZofge61MiOO2ko=
  file:
    - "build/libs/hm2mqtt.jar"
    - "build/distributions/hm2mqtt-addon.tar.gz"
  skip_cleanup: true
  on:
    repo: hangy/hm2mqtt
    tags: true
    all_branches: true
